### ISSUE TITLE
RuntimeError: bool value of Tensor with more than one value is ambiguous

### ISSUE THREAD

**Issue by J14032016** [Atcold/pytorch-MatchNet#10]
While running your code：“DiscriminativeCell.py",, I encountered this error：
line 35, in forward
    input_projection = self.first and bottom_up or f.relu(f.max_pool2d(self.from_bottom(bottom_up), POOL, POOL))
RuntimeError: bool value of Tensor with more than one value is ambiguous。

Can you give me any hint to solve?
Thank you very much.

**Comment by Atcold** [comment]
https://github.com/Atcold/pytorch-CortexNet/issues/3

**Comment by Atcold** [comment]
You can see how to fix it here -> https://github.com/Atcold/pytorch-CortexNet/issues/8
If you do fix it, please, send a PR. Thanks!
