### ISSUE TITLE
System Specifications Required

### ISSUE THREAD

**Issue by Ysmita** [Atcold/pytorch-MatchNet#11]
Hi @Atcold 
I am very interested in this work and would like to implement this. Could you please reply the specifications of the system which you used for training?

**Comment by Atcold** [comment]
A machine with a GeForce GTX TITAN X 12G (Pascal) would suffice. What do you have, currently?

**Comment by Ysmita** [comment]
Currently I have Nvidia Quadro K5000  4GB and CPU having 64GB RAM.

**Comment by Atcold** [comment]
4GB are a bit tight, but I think it should be just fine.
At worse, you can reduce the batch size.
Just try to run it (there are a few things you need to fix, to make it work the the latest version of PyTorch, see other issues).
Let me know if you need anything else.

**Comment by Atcold** [comment]
Here you have the full specs list. I hope it helps.

 - [CPU](https://www.newegg.com/Product/Product.aspx?Item=N82E16819117647)
 - [Case](https://www.newegg.com/Product/Product.aspx?Item=N82E16811139024)
 - [MoBo](https://www.newegg.com/Product/Product.aspx?Item=N82E16813130921)
 - [RAM](https://www.newegg.com/Product/Product.aspx?Item=N82E16820104678)
 - [CPU cooler](https://www.newegg.com/Product/Product.aspx?Item=N82E16835181102)
 - [SSD](https://www.newegg.com/Product/Product.aspx?Item=9SIA12K54C9643)
 - [2x SSD (storage)](https://www.newegg.com/Product/Product.aspx?Item=N82E16820147374)
 - [PSU](https://www.newegg.com/Product/Product.aspx?Item=9SIA1K656T0897)
