### ISSUE TITLE
Execution error with network_bisection.ipynb

### ISSUE THREAD

**Issue by jasonachonu** [Atcold/pytorch-MatchNet#13]
Running the code in `network_bisection.ipynb` I found an error in the code:

```python
my_embedding = torch.zeros(512)
def fun(m, i, o): my_embedding.copy_(o.data)
h = avgpool_layer.register_forward_hook(fun)
h_x = resnet_18(x)
h.remove()
```

`RuntimeError: expand(torch.FloatTensor{[1, 512, 1, 1]}, size=[512]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (4)`

**Comment by Atcold** [comment]
I've updated the notebook you pointed to PyTorch 1.0.
