### ISSUE TITLE
Data Parallel for ConvLSTM

### ISSUE THREAD

**Issue by luoxijing** [Atcold/pytorch-MatchNet#17]
Hi,Thanks for sharing great work!

I want to train my model with convLSTMcell Layer on multiple GUPs, but how do I do that?
I'd appreciate it if you could give me a tip! Thanks!

**Comment by Atcold** [comment]
I've never used multiple GPUs.
You may want to check [PyTorch documentation](https://pytorch.org/tutorials/beginner/former_torchies/parallelism_tutorial.html).
