### ISSUE TITLE
Regarding the datasets and pre-trained model weights

### ISSUE THREAD

**Issue by freshcoffee22** [Atcold/pytorch-MatchNet#18]
Hello, it seems that the data link provided in your readme cannot be accessed at ftp://elab-board2.ecn.purdue.edu/e-VDS/e-VDS35-May17.tar. Additionally, I was wondering if you have any pre-trained model weights available?

**Comment by Atcold** [comment]
This project is now defunct. Perhaps I should retire the repo.
