### ISSUE TITLE
Can't load in pre-trained model

### ISSUE THREAD

**Issue by wingz1** [Atcold/pytorch-MatchNet#6]
I'd like to extract features from trained model in MatchNet mode, but it won't load the pretrained model in.

```
    49     print('Load pre-trained weights')
    50     # args.pre_trained = 'image-pretraining/model02D-33IS/model_best.pth.tar'
--> 51     dict_33 = torch.load(args.pre_trained)['state_dict']

TypeError: 'Model02' object is not subscriptable

In [10]: args.pre_trained
Out[10]: './last/model.pth.tar'
```

Any ideas?   the training never saved a "model_best.pth.tar" file, only a model.pth.tar

**Comment by Atcold** [comment]
You have that ([ref.](https://github.com/Atcold/pytorch-CortexNet/blob/master/image-pretraining/main.py#L234-L237))

```python
def save_checkpoint(state, is_best, filename='checkpoint.pth.tar'):
    torch.save(state, filename)
    if is_best:
        shutil.copyfile(filename, 'model_best.pth.tar')
```

will save a file named `model_best.pth.tar` when `is_best == True` ([ref.](https://github.com/Atcold/pytorch-CortexNet/blob/master/image-pretraining/main.py#L131-L138))

```python
# remember best prec@1 and save checkpoint
is_best = prec1 > best_prec1
best_prec1 = max(prec1, best_prec1)
save_checkpoint({
    'epoch': epoch + 1,
    'state_dict': model.state_dict(),
    'best_prec1': best_prec1,
}, is_best)
```

So, I guess your training procedure has a decreasing accuracy over time trend?

Hold on, you get `model.pth.tar`??? I was expecting you to tell me you were getting `checkpoint.pth.tar` instead. What code are you actually running?
