### ISSUE TITLE
Trying to train MatchNet but getting issues output loss calculation.

### ISSUE THREAD

**Issue by mukunda11** [Atcold/pytorch-MatchNet#8]
[MatchNet_output_error.txt](https://github.com/Atcold/pytorch-CortexNet/files/1905485/MatchNet_output_error.txt)
[MatchNet_output.txt](https://github.com/Atcold/pytorch-CortexNet/files/1905486/MatchNet_output.txt)

**Comment by mukunda11** [comment]
I see that someone else had this issue before.  Unfortunately, I will not be able to redownload pytorch with pip because I do not have sudo access to the server.  I hope there is another way to solve the problem.

**Comment by Atcold** [comment]
So, the error you're getting is
```python
File "/depot/chubykin/gpu/pytorch-CortexNet-master/model/Model02.py", line 76, in forward
    s = state[layer - 1] or V(x.data.clone().zero_())
    torch.typename(self.data) + " is ambiguous")
RuntimeError: bool value of Variable objects containing non-empty torch.cuda.FloatTensor is ambiguous
```
where it used to be legal to check if an `object` was not `None`.
Now you have to rewrite
```python
s = state[layer - 1] or V(x.data.clone().zero_())
```
as
```python
s = state[layer - 1] if state[layer - 1] is not None else V(x.data.clone().zero_())
```
This should solve your issue.
If it does, you're more then welcome to send a PR fixing this and similar deprecated syntaxes.

If my reply fixes your problem, you can close this issue.

**Comment by mukunda11** [comment]
Thank you! That fixed the error. However, I am getting the same error for another line.
Is there a similar issue for this function in the main.py file?
![image](https://user-images.githubusercontent.com/31289375/39333139-c32b688a-4977-11e8-8255-08c74429b510.png)

**Comment by Atcold** [comment]
Please, don't upload pictures... Just type code and enclose it in three back-ticks ```. You can add the language too by typing `python` after the ticks.

Anyhow, yes, replace `if not h` with `if h is None`.

Also, if you installed the latest PyTorch (version `0.4.0`), then `return V(h.data)` should be replaced by `return h.detach()`.

**Comment by mukunda11** [comment]
Apologies for the picture.  Thank you for the quick response.
