### ISSUE TITLE
Issue about ConvLstm

### ISSUE THREAD

**Issue by devraj89** [Atcold/pytorch-MatchNet#9]
Hi Atcold

Thanks for the wonderful code and also the wonderful tutorials on pytroch!
I actually have a doubt -- 
I read two articles detailing the ConvLstm model in 
[1] https://en.wikipedia.org/w/index.php?title=Long_short-term_memory&oldid=784163987#cite_note-20
[2] https://arxiv.org/pdf/1506.04214.pdf -- equation (3)

In both the above models, while computing the input, forget and output gates, they have used the previous cell states i.e `prev_cell` whereas you have not used. Can you please tell me why not ?

Thanks
Devraj

**Comment by Atcold** [comment]
See [Wikipedia](https://en.wikipedia.org/wiki/Long_short-term_memory#LSTM_with_a_forget_gate), where you replace the matrix-multiplication with a convolution.
The variant using the cell state is called [*peephole*](https://en.wikipedia.org/wiki/Long_short-term_memory#Peephole_LSTM).
The following variant, which they call convolutional LSTM, is actually a peephole convolutional LSTM.
